//
// Created by giuseppe on 25/11/19.
//

#include "error.h"

int printError(int error, const string& nameFunction) {

    switch (error) {
        case GENERIC_ERROR:
            cout << endl << BOLDMAGENTA << "ERROR! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case MEMORY_ERROR:
            cout << endl << BOLDMAGENTA <<  "ERROR! Not enough memory! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case FILE_ERROR:
            cout << endl << BOLDMAGENTA <<  "ERROR! Error while opening file! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case SKETCH_ERROR:
            cout << endl << BOLDMAGENTA <<  "ERROR! The sketch data structure is not valid! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case MERGE_ERROR:
            cout << endl << BOLDMAGENTA <<  "ERROR! The sketches can't be merged! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case QUANTILE_ERROR:
            cout << endl << BOLDMAGENTA <<  "ERROR! The inserted quantile isn't in the [0,1] range! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case UNKNOWN_COLLAPSE_TYPE:
            cout << endl << BOLDMAGENTA <<  "ERROR! The collapse type code inserted is wrong ! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case COPY_ERROR:
            cout << endl << BOLDMAGENTA <<  "ERROR! Error copying arrays! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case NULL_POINTER_ERROR:
            cout << endl << BOLDMAGENTA << "ERROR! Null pointer error! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case GRAPH_GENERATION_ERROR:
            cout << endl << BOLDMAGENTA << "ERROR! Graph generation error! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case UNKNOWN_GRAPH_TYPE:
            cout << endl << BOLDMAGENTA << "ERROR! Unknown graph type! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case PARAM_ERROR:
            cout << endl << BOLDMAGENTA << "ERROR! The param data structure is not valid! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case USAGE_ERROR:
            cout << endl << BOLDMAGENTA << "ERROR! Usage error! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case DATASET_DIVISION_ERROR:
            cout << endl << BOLDMAGENTA << "ERROR! Dataset division error! Generated by " << nameFunction << " function" << RESET << endl;
            break;
        case CONFLICTING_OPTIONS:
            cout << endl << BOLDMAGENTA << "ERROR! Conflicting options! Generated by " << nameFunction << " function" << RESET << endl;
            break;
    }

    return 0;
}